name: Deploy static site to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip static files
        run: |
          mkdir site
          cp index.html script.js style.css -t site/
          cp -r images site/images
          zip -r site.zip site

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: drawbridgewebuk  # Replace with your exact Azure Web App name
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: site.zip
